#!/usr/bin/env python3

import base64
import urllib.parse
import sys
import zlib

import lxml.etree


if len(sys.argv) != 2:
    print("Usage: " + sys.argv[0] + " saml_request_string")
    sys.exit(1)

base64_saml_request = urllib.parse.unquote(sys.argv[1])
compressed_saml_request = base64.b64decode(base64_saml_request)
saml_request = zlib.decompress(compressed_saml_request, wbits=-8)

if isinstance(saml_request, bytes):
    saml_request = saml_request.decode('utf-8')

root = lxml.etree.fromstring(saml_request)
print(lxml.etree.tostring(root, pretty_print = True, encoding = str))
