#!/bin/bash

declare -r PWGEN="pwgen --ambiguous --secure"
declare -r MIN_GROUP_LENGTH=4
declare -r MAX_GROUP_LENGTH=8

declare length=20
declare separators="-"
declare newpass=""

while [[ -n $* ]]; do
    if [[ $1 =~ ^[1-9][0-9]*$ ]]; then
        length=$1
    else
        separators="$1"
    fi
    shift
done

if [[ $length -le 10 ]]; then
    newpass="$($PWGEN "$length" 1)"
else
    while [[ ${#newpass} -lt $length ]]; do
        if [[ $((${#newpass} + MIN_GROUP_LENGTH * 2 + 1)) -gt $length ]]; then
            # not enough remaining for two groups of smallest length plus separator
            grouplen=$((length - ${#newpass}))
        else
            while : ; do
                grouplen=$((RANDOM % $((MAX_GROUP_LENGTH - MIN_GROUP_LENGTH + 1)) + MIN_GROUP_LENGTH))
                [[ $((${#newpass} + grouplen + MIN_GROUP_LENGTH + 1)) -le $length ]] && break
            done
        fi

        group="$(PWGEN "$grouplen" 1)"
        newpass="${newpass}${group}"

        if [[ ${#newpass} -lt $length ]]; then
            separator="$separators"
            if [[ ${#separators} -gt 1 ]]; then
                index=$((RANDOM % ${#separators}))
                echo "Using $index of $separators"
                separator="${separators:$index:1}"
                echo "separator=$separator"
            fi
            newpass="${newpass}${separator}"
        fi
    done
fi

echo -n "$newpass"
echo >&2
