#!/usr/bin/env python3


import configparser
import os
import re
import sys


CREDENTIALS_FILE = os.path.expanduser('~/.aws/credentials')
AWS_SETTING = re.compile(r'''
    (export|SET)
    \s*
    (?P<k>AWS_(ACCESS_KEY_ID|SECRET_ACCESS_KEY|SESSION_TOKEN))
    \s*
    =
    \s*
    "(?P<v>[^"]+)"
    ''', re.VERBOSE)


if len(sys.argv) != 2:
    print('Usage: {} aws/profile'.format(sys.argv[0]))
    sys.exit(255)

profile = sys.argv[1]

config = configparser.ConfigParser()
config.read(CREDENTIALS_FILE)

if profile not in config.keys():
    print('Unknown profile {}'.format(profile))
    sys.exit(255)

while True:
    try:
        line = input()
    except EOFError:
        break

    match = AWS_SETTING.match(line)
    if match:
        k = match.group('k').lower()
        v = match.group('v')
        config[profile][k] = v

config_file = open(CREDENTIALS_FILE, 'r+')
config.write(config_file)
config_file.close()
